# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 君问
email: jjvein@gmail.com 
excerpt: 君问,君问归期未有期,jjvein,君问博客
description: > # this means to ignore newlines until "baseurl:"
  <strong>君问归期未有期， 巴山夜雨涨秋池.</strong> <br/>
  该Blog的文章有自己开发de心得， 有copy其他优秀文章，还有个人利用闲暇时间翻译的技术文档，若有侵权行为，请通知me。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jjvein.github.com" # the base hostname & protocol for your site
github_username:  jjvein


# Build settings
markdown: kramdown

tag_page_layout: post
tag_page_dir: tag
